# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_student.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Students(object):
    def setupUi(self, Students):
        Students.setObjectName("Students")
        Students.resize(945, 568)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/imgs/logo_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Students.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Students)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.index_page = QtWidgets.QPushButton(self.centralwidget)
        self.index_page.setObjectName("index_page")
        self.horizontalLayout_3.addWidget(self.index_page)
        self.before_page = QtWidgets.QPushButton(self.centralwidget)
        self.before_page.setObjectName("before_page")
        self.horizontalLayout_3.addWidget(self.before_page)
        self.page_input = QtWidgets.QLineEdit(self.centralwidget)
        self.page_input.setMaximumSize(QtCore.QSize(69, 16777215))
        self.page_input.setAlignment(QtCore.Qt.AlignCenter)
        self.page_input.setObjectName("page_input")
        self.horizontalLayout_3.addWidget(self.page_input)
        self.next_page = QtWidgets.QPushButton(self.centralwidget)
        self.next_page.setObjectName("next_page")
        self.horizontalLayout_3.addWidget(self.next_page)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_3)
        self.clear_button = QtWidgets.QPushButton(self.centralwidget)
        self.clear_button.setObjectName("clear_button")
        self.horizontalLayout_2.addWidget(self.clear_button)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.search_input = QtWidgets.QLineEdit(self.centralwidget)
        self.search_input.setText("")
        self.search_input.setObjectName("search_input")
        self.horizontalLayout_2.addWidget(self.search_input)
        self.search_button = QtWidgets.QPushButton(self.centralwidget)
        self.search_button.setObjectName("search_button")
        self.horizontalLayout_2.addWidget(self.search_button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.info_table = QtWidgets.QTableWidget(self.centralwidget)
        self.info_table.setObjectName("info_table")
        self.info_table.setColumnCount(6)
        self.info_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.info_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.info_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.info_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.info_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.info_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.info_table.setHorizontalHeaderItem(5, item)
        self.verticalLayout.addWidget(self.info_table)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.stu = QtWidgets.QLineEdit(self.centralwidget)
        self.stu.setObjectName("stu")
        self.horizontalLayout.addWidget(self.stu)
        self.name = QtWidgets.QLineEdit(self.centralwidget)
        self.name.setObjectName("name")
        self.horizontalLayout.addWidget(self.name)
        self.build = QtWidgets.QLineEdit(self.centralwidget)
        self.build.setObjectName("build")
        self.horizontalLayout.addWidget(self.build)
        self.password = QtWidgets.QLineEdit(self.centralwidget)
        self.password.setObjectName("password")
        self.horizontalLayout.addWidget(self.password)
        self.add_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_button.setStyleSheet("")
        self.add_button.setAutoDefault(False)
        self.add_button.setDefault(True)
        self.add_button.setFlat(False)
        self.add_button.setObjectName("add_button")
        self.horizontalLayout.addWidget(self.add_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        Students.setCentralWidget(self.centralwidget)

        self.retranslateUi(Students)
        QtCore.QMetaObject.connectSlotsByName(Students)

    def retranslateUi(self, Students):
        _translate = QtCore.QCoreApplication.translate
        Students.setWindowTitle(_translate("Students", "Password Manage"))
        self.index_page.setText(_translate("Students", "Index"))
        self.before_page.setText(_translate("Students", "Previous"))
        self.page_input.setText(_translate("Students", "1"))
        self.next_page.setText(_translate("Students", "Next"))
        self.clear_button.setText(_translate("Students", "clear"))
        self.label_2.setText(_translate("Students", "Search:"))
        self.search_input.setPlaceholderText(_translate("Students", "keyword"))
        self.search_button.setText(_translate("Students", "Search"))
        item = self.info_table.horizontalHeaderItem(0)
        item.setText(_translate("Students", "Name"))
        item = self.info_table.horizontalHeaderItem(1)
        item.setText(_translate("Students", "Url"))
        item = self.info_table.horizontalHeaderItem(2)
        item.setText(_translate("Students", "Username"))
        item = self.info_table.horizontalHeaderItem(3)
        item.setText(_translate("Students", "Password"))
        item = self.info_table.horizontalHeaderItem(4)
        item.setText(_translate("Students", "Modify"))
        item = self.info_table.horizontalHeaderItem(5)
        item.setText(_translate("Students", "Delete"))
        self.label.setText(_translate("Students", "Insert Password:"))
        self.stu.setPlaceholderText(_translate("Students", "Name"))
        self.name.setPlaceholderText(_translate("Students", "Url(null)"))
        self.build.setPlaceholderText(_translate("Students", "Username"))
        self.password.setPlaceholderText(_translate("Students", "Password"))
        self.add_button.setText(_translate("Students", "Insert"))


import img_rc
